### ISSUE TITLE
Change the port number on localhost

### ISSUE THREAD

**Issue by doutv** [09wattry/vim-adventures-rev#2]
I run the program on Win10 and there is a error message saying that port 80 requires elevated privileges. I try running it on administrator mode but the error stays. I change the port number in `/bin/www.js ` from 80 to 8080 and it works for me.
```js
var port = normalizePort(process.env.PORT || '8080');
```

**Comment by 09wattry** [comment]
Yes, lower ports are protected. You can use 8080 or any high port and it will work

**Comment by gra4ina** [comment]
Hello there!
I've tried to install your package on Win10, but I faced the next problem:

```
C:\Users\abafel\Documents\vim-adventures-rev-master>.\vim-adventures-win.exe -v
pkg/prelude/bootstrap.js:1248
      throw error;
      ^

Error: Cannot find module 'http-errors'
Require stack:
- C:\snapshot\vim-adventures-rev-master\app.js
- C:\snapshot\vim-adventures-rev-master\bin\www
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)[39m
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1350:46)
[90m    at Function.Module._load (internal/modules/cjs/loader.js:862:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1042:19)[39m
    at Module.require (pkg/prelude/bootstrap.js:1229:31)
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\snapshot\vim-adventures-rev-master\app.js)
    at Module._compile (pkg/prelude/bootstrap.js:1324:22)
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1000:32)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\snapshot\\vim-adventures-rev-master\\app.js'[39m,
    [32m'C:\\snapshot\\vim-adventures-rev-master\\bin\\www'[39m
  ],
  pkg: [33mtrue[39m
}
```

I'm actually not a computer guru, but I tried to find some ways to resolve and I couldn't find anything on google. Could you advise something? Thanks in advance.

**Comment by pycprince** [comment]
@gra4ina, a word of advice: You shouldn't piggy back off of other issues. Your question should be posted as a separate issue.

I ran into this same error. Running "./vim-adventures" did not work for me. I did however get this to work by navigating to my home directory and seeing "vim-adventure" directory. After following the readme, I did the following:
1. `..` (in bash you need `cd ..`)
2. `ls -a` (saw there was a "vim-adventures" dir)
3. `vim-adventures`
4. Navigated to my browser and typed `http://localhost` (and here is the game now)
5. Navigated back to terminal and typed `Ctrl-c` when I was finished

**Comment by 09wattry** [comment]
@gra4ina thanks for your interest in the project. As @pycprince suggested please move your comment to a new issue so that we don't pollute the other user's query. I would gladly help you if you get back to me like there.

**Comment by 09wattry** [comment]
> I run the program on Win10 and there is a error message saying that port 80 requires elevated privileges. I try running it on administrator mode but the error stays. I change the port number in `/bin/www.js ` from 80 to 8080 and it works for me.
> 
> ```js
> var port = normalizePort(process.env.PORT || '8080');
> ```

This is expected behavior, however, running the package in admin mode should resolve this. I do not have a way to have users set a port other than update the code in bin/www.js as of this moment. I am going to close this issue as there has not been any response.
